import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";

const Home: NextPage = () => {
  
  return (
    <>
      <div >
        <Head>
          <title>learn nextjs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
       <Hero heading='Manchester United' message='Glory Glory Man United'/>
       <Slider slides={SliderData}/>
      </div>
    </>
  );
};

export default Home;
