import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { MainLayout } from "../components/layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  function goToDetailProductPage() {
    router.push({
      pathname: "/products/create",
      query: {
        productId: 123,
        ref: "product",
      },
    });
  }
  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Luận Văn Tốt Nghiệp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>Hello , my name is Truong</p>
          <Link href="/about">
            <a>go to about</a>
          </Link>
          <button onClick={goToDetailProductPage}>
            Go to index product detail page
          </button>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </MainLayout>
  );
};

export default Home;
